### ISSUE TITLE
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD

### ISSUE THREAD

**Issue by xiekunwhy** [StuntsPT/pyRona#12]
Hi,

When I run pyRona using test data, I always get MKL error, do you have any suggestions to solved this problem ?
command line I use: "/Bio/User/kxie/software/anaconda3/bin/pyRona lfmm -pc LFMM_covars.txt -fc LFMM_RCP26_covars.txt -out LFMM_rpc26.pdf -P 0.01 -assoc Qsuber_lfmm_results.csv -geno Qsuber.lfmm".
and the error I get:
Intel MKL ERROR: Parameter 6 was incorrect on entry to DGELSD.
Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/bin/pyRona", line 8, in <module>
    sys.exit(main())
  File "/Bio/User/kxie/software/anaconda3/lib/python3.7/site-packages/pyRona/pyRona.py", line 234, in main
    arg.plots, arg.outliers, arg.rtype)
  File "/Bio/User/kxie/software/anaconda3/lib/python3.7/site-packages/pyRona/pyRona.py", line 110, in calculate_rona
    fit = np.polyfit(present_covar[not_nan], allele_freqs[not_nan], 1)
  File "<__array_function__ internals>", line 6, in polyfit
  File "/Bio/User/kxie/software/anaconda3/lib/python3.7/site-packages/numpy/lib/polynomial.py", line 629, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 6, in lstsq
  File "/Bio/User/kxie/software/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
  File "/Bio/User/kxie/software/anaconda3/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 100, in _raise_linalgerror_lstsq
    raise LinAlgError("SVD did not converge in Linear Least Squares")
numpy.linalg.LinAlgError: SVD did not converge in Linear Least Squares

Best,
Kun

**Comment by StuntsPT** [comment]
Hi @xiekunwhy 
I have tried to run your command, but it works as expected on my end.
Can you please try again using a new (and empty) conda environment?

```bash
conda create -n pyrona
conda activate pyrona
conda install python
pip uninstall pyrona
pip install pyrona
/Bio/User/kxie/software/anaconda3/bin/pyRona lfmm -pc LFMM_covars.txt -fc LFMM_RCP26_covars.txt -out LFMM_rpc26.pdf -P 0.01 -assoc Qsuber_lfmm_results.csv -geno Qsuber.lfmm
```

Best,

Francisco

**Comment by xiekunwhy** [comment]
Hi Francisco

It works, thank you for your answers.

Best,
Kun

**Comment by StuntsPT** [comment]
Glad that worked.
Enjoy your genomic offset analyses! =-)
