### ISSUE TITLE
Some erros with pyRona

### ISSUE THREAD

**Issue by zlc952** [StuntsPT/pyRona#14]
Hi,

When I run pyRona using my data, I always get some errors, do you have any suggestions to solved this problem ?
command line I use: "pyRona lfmm -pc 4bio_current_env_pop.txt -fc 4bio_access_cm2_ssp126.txt -out LFMM_cm2_ssp126.pdf -P 0.00001 -assoc 4bio_scale_p.csv -geno 140ld.lfmm.
and the error I get:
Traceback (most recent call last):
  File "/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/bin/pyRona", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/pyRona.py", line 221, in main
    assocs = fp.lfmm_results_parser(arg.lfmm_assoc_file,
                                    arg.p_thres,
                                    arg.immutables,
                                    covar_names)
  File "/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/file_parser.py", line 130, in lfmm_results_parser
    if float(j) < assoc_threshold and i not in imut_indeces]
       ~~~~~^^^
ValueError: could not convert string to float: ''

Thanks!

**Comment by StuntsPT** [comment]
Hi @zlc952,
I *suspect* this might be an issue with the provided LFMM file, as the error is in the LFMM parsing module (where python is trying, and failing, to convert an empty string to a float).
Can I please have a sample of your LFMM file (such as the first 10 lines?).
If you are not comfortable sharing that subset of your data publicly, you can share it by email.

Best,

Francisco

**Comment by zlc952** [comment]
Hi@StuntsPT,
Thank you for your constructive help. My previous issue has been resolved, and Pyrona is running normally. However, the results are not satisfactory, as the Rona values are showing as nan. Could you please explain what might be causing this? Below are my command and the results.
(/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona) [pc@localhost rona]$ pyRona lfmm -covars 3 -pc 3bio_current_env_pop.txt -fc 3bio_access_cm2_ssp126.txt -out access_cm2_ssp126.pdf -P 0.00001 -assoc 3bio_scale_p.csv -geno 140ld.lfmm
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/pyRona.py:129: RuntimeWarning: invalid value encountered in scalar divide
  rel_distance = abs(distance_diff) / amplitude
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/pyRona.py:129: RuntimeWarning: divide by zero encountered in scalar divide
  rel_distance = abs(distance_diff) / amplitude
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/_core/_methods.py:194: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
Covar	1	3	2
#SNPs	8079	8079	8078
JK	0.37784829505516987	0.0	nan
SS	0.3747895855317136	nan	0.8690165166921731
JMS	0.15918715833333386	nan	0.13672427155758518
BHS	0.14835866157384642	nan	0.9935357383183283
BJS	0.038388454130629635	nan	0.21437497976090267
WTS	0.28637434839835707	nan	0.3483341092622124
HDL	0.8070378211326669	nan	nan
Min R^2	6.931623466603578e-06	0.0	2.1983046674404862e-06
Max R^2	0.9361596286876258	0.9199004975124376	0.92054654509266
Average R^2	0.15319647067415754	0.18048080728445173	0.15823418470500472

**Comment by zlc952** [comment]
Hi @StuntsPT ,
Thank you for your constructive help. My previous issue has been resolved, and Pyrona is running normally. However, the results are not satisfactory, as the Rona values are showing as nan. Could you please explain what might be causing this? Below are my command and the results.
```
(/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona) [pc@localhost rona]$ pyRona lfmm -covars 3 -pc 3bio_current_env_pop.txt -fc 3bio_access_cm2_ssp126.txt -out access_cm2_ssp126.pdf -P 0.00001 -assoc 3bio_scale_p.csv -geno 140ld.lfmm
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:2999: RuntimeWarning: invalid value encountered in divide
c /= stddev[:, None]
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/lib/_function_base_impl.py:3000: RuntimeWarning: invalid value encountered in divide
c /= stddev[None, :]
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/pyRona.py:129: RuntimeWarning: invalid value encountered in scalar divide
rel_distance = abs(distance_diff) / amplitude
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/pyRona/pyRona.py:129: RuntimeWarning: divide by zero encountered in scalar divide
rel_distance = abs(distance_diff) / amplitude
/data_MU/zlc/1/GBS_pre/vcf/rona/Anaconda/pyrona/lib/python3.13/site-packages/numpy/_core/_methods.py:194: RuntimeWarning: invalid value encountered in subtract
x = asanyarray(arr - arrmean)
Covar 1 3 2
#SNPs 8079 8079 8078
JK 0.37784829505516987 0.0 nan
SS 0.3747895855317136 nan 0.8690165166921731
JMS 0.15918715833333386 nan 0.13672427155758518
BHS 0.14835866157384642 nan 0.9935357383183283
BJS 0.038388454130629635 nan 0.21437497976090267
WTS 0.28637434839835707 nan 0.3483341092622124
HDL 0.8070378211326669 nan nan
Min R^2 6.931623466603578e-06 0.0 2.1983046674404862e-06
Max R^2 0.9361596286876258 0.9199004975124376 0.92054654509266
Average R^2 0.15319647067415754 0.18048080728445173 0.15823418470500472
```

Thanks again for your assistance!!

**Comment by StuntsPT** [comment]
Humm... I don't recall having seen these warnings before.
In order to understand the issue, I will need a minimal test case. Can you please share with me a **small** subset of your data that causes the issue? I would require a subsample of each of the used files. You can, of course, anonimize them before sharing.
Also, my apologies for having closed the issue. It was not my intention.

**Comment by zlc952** [comment]
> Humm... I don't recall having seen these warnings before. In order to understand the issue, I will need a minimal test case. Can you please share with me a **small** subset of your data that causes the issue? I would require a subsample of each of the used files. You can, of course, anonimize them before sharing. Also, my apologies for having closed the issue. It was not my intention.

Hello! Thank you very much for your previous reply.
 May I ask what data you need? Does it include lfmm, p-values, as well as current and future environmental data?

**Comment by StuntsPT** [comment]
Sorry, I seem to have missed this notification.
Yes please, I will need all that data (preferably a minimal, anonymized, file) and the command you used with to so I can reproduce the issue locally.
Thank you!
